### ISSUE TITLE
TTL set on column table can delete fresher data than requested

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#13523]
1. Cоздаём таблицу
```
CREATE TABLE `olap_tests/delete_s3_ttl/table` (
        ts Timestamp NOT NULL,
        s String,
        val Uint64,
        PRIMARY KEY(ts),
    )
    WITH (STORE = COLUMN)
```
2. заполняем данными с равномерно респределённым PK за одну операцию записи
```
$row_count = 1000000;
$from_us = CAST(Timestamp('2010-01-01T00:00:00.000000Z') as Uint64);
$to_us = CAST(Timestamp('2030-01-01T00:00:00.000000Z') as Uint64);
$dt = $to_us - $from_us;
$k = ((1ul << 64) - 1) / CAST($dt - 1 as Double);
$rows= ListMap(ListFromRange(0, $row_count), ($i)->{ 
    $us = CAST(RandomNumber($i) / $k as Uint64) + $from_us;
    $ts = Unwrap(CAST($us as Timestamp));
    return <|
        ts: $ts,
        s: 'some date:' || CAST($ts as String),
        val: $us 
    |>;
});
upsert into `olap_tests/delete_s3_ttl/table`
select * FROM AS_TABLE($rows);
```
3. Убеждаемся, что есть строки, свежее, чем 1000 дней
```
select count(*) from `olap_tests/delete_s3_ttl/table` where ts > CurrentUtcTimestamp() - Interval("P1000D")
```
Напр., 383941. Может быть другое значение
4. Включаем TTL
```
ALTER TABLE `olap_tests/delete_s3_ttl/table` SET (TTL = Interval("P1000D") on ts)
```
5. Ждём, когда данные начнут удаляться по TTL
для ускорения я выставлял опции:
```
column_shard_config:
  disabled_on_scheme_shard: false
  lag_for_compaction_before_tierings_ms: 0
  compaction_actualization_lag_ms: 0
  optimizer_freshness_check_duration_ms: 0
  small_portion_detect_size_limit: 0
```
6. Проверяем, сколько строк осталось:
```
select count(*) from `olap_tests/delete_s3_ttl/table`
```
Получается 0
