### ISSUE TITLE
Only cluster admin can access auth system views inside database

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/ydb#14234]
# Steps to reproduce

1) Deploy cluster with this `security_config` (also called `security_settings` in old style cfg):
```
security_settings:
    default_users:
      - name: root
        password: ""
    default_groups:
      - name: ADMINS
        members:
          - root
    default_access:
      - "+F:root"
      - "+F:ADMINS"

    viewer_allowed_sids:
      - root
      - ADMINS
    monitoring_allowed_sids:
      - root
      - ADMINS
    administration_allowed_sids:
      - root
      - ADMINS
```

2) Create database `/Root/db1`

3) Create database admin group and make it owner of the database

```
ydb -e <endpoint> -d '/Root/db1' yql -s '
    CREATE GROUP `dbadmins`;
'

ydb -e <endpoint> -d '/Root/db1' yql -s '
    CREATE USER `dbadmin1` PASSWORD "1234";
'

ydb -e <endpoint> -d '/Root/db1' yql -s '
    ALTER GROUP `dbadmins` ADD USER
        `dbadmin1`
'

/ydb -e <endpoint>  -d '/Root/db1' scheme permissions chown /Root/db1 dbadmins
```

4) Try to select from system view
```
ydb -e <endpoint> -d /Root/db1 --user dbadmin1 table query execute -q 'SELECT * FROM `/Root/db1/.sys/auth_group_members`'
```

It returns error:
```
Status: INTERNAL_ERROR
Issues:
<main>: Error: Administrator access is required
<main>: Error: Query invalidated on scheme/internal error during Data execution, code: 2019
```

https://github.com/ydb-platform/ydb/blob/6cd0f50b87515eba2db841a4a74a7834f6aac684/ydb/core/sys_view/auth/auth_scan_base.h#L88
