### ISSUE TITLE
Can't restore database backup if table inside database owned by cluster admin

### ISSUE THREAD

**Issue by pixcc** [ydb-platform/ydb#14790]
# Steps to reproduce

1) Deploy cluster with this `security_config` (also called `security_settings` in old style cfg):
```
security_settings:
    default_users:
      - name: root
        password: ""
    default_groups:
      - name: ADMINS
        members:
          - root
    default_access:
      - "+F:root"
      - "+F:ADMINS"

    viewer_allowed_sids:
      - root
      - ADMINS
    monitoring_allowed_sids:
      - root
      - ADMINS
    administration_allowed_sids:
      - root
      - ADMINS

auth:
  domain_login_only: false

features:
  enable_strict_acl_check: true
  database_yaml_config_allowed: true
  enable_strict_user_management: true
  enable_database_admin: true
```

2) Create database `/Root/db1`

3) Get token for `root`
```
ydb -e <endpoint> --user root --no-password -d '/Root' auth get-token -f > root_token
```

4)  Create table inside database that owned by cluster admin
```
ydb -e <endpoint> --token-file root_token -d '/Root/db1' yql -s '
    CREATE TABLE `MyTable`(
        Id int,
        PRIMARY KEY(ID)
    )
'
```

5) Backup database `/Root/db1`
```
ydb -e <endpoint> -d /Root/db1 --token-file root_token admin database backup -o backup_db
```

6) Restore database to `/Root/db2`

```
ydb -e <endpoint> -d /Root/db2 --token-file root_token admin database restore -i backup_db
```

It returns error:
```
2025-02-19T11:28:55.562160Z :INFO: Restore table "backup_db/MyTable" to "/Root/db2/MyTable"
2025-02-19T11:28:55.668832Z :ERROR: Restore database failed: { <main>: Error: Owner SID root not found in database `/Root/db2` }
Status: PRECONDITION_FAILED
Issues:
<main>: Error: Owner SID root not found in database `/Root/db2`
```
