### ISSUE TITLE
Ошибка "database doesn't have storage pools" после перезапуска контейнера с YDB_USE_IN_MEMORY_PDISKS=true (YDB 24.4.4.2.fd1e65b, Colima, Apple Silicon)

### ISSUE THREAD

**Issue by vladkolotvin** [ydb-platform/ydb#17760]
Здравствуйте!

Я запускаю YDB (версия 24.4.4.2.fd1e65b) в Docker через Colima с поддержкой Rosetta и virtiofs на MacBook с Apple M1 Pro (macOS 14.2.1).
Никакие volume для данных YDB не монтируются (ни /ydb_data, ни /ydb_certs и т.д.).

Проблема:
- При первом запуске контейнера всё работает корректно, storage pool создаётся, таблицы создаются, миграции применяются.
- После остановки и повторного запуска контейнера появляется ошибка:
  database doesn't have storage pools at all to create tablet channels to storage pool binding by profile id
- Если удалить контейнер и создать новый — снова всё работает, но только до следующего перезапуска.

Минимальный docker-compose.yaml:
```yaml
ydb:
  image: cr.yandex/yc/yandex-docker-local-ydb:latest
  environment:
    - YDB_USE_IN_MEMORY_PDISKS=true
    - GRPC_PORT=2136
    - MON_PORT=8765
  ports:
    - "8765:8765"
```

Ожидание:
YDB должен корректно стартовать после любого количества перезапусков контейнера в in-memory режиме, если не используются volume для данных.

Окружение:
- Docker: Colima (с поддержкой Rosetta и virtiofs)
- Хост: MacOS 14.2.1
- Процессор: Apple M1 Pro
- Версия YDB: 24.4.4.2.fd1e65b

Логи:
(приложу по запросу)
