### ISSUE TITLE
Запускать regression только из main

### ISSUE THREAD

**Issue by naspirato** [ydb-platform/ydb#19498]
вот тут https://github.com/ydb-platform/ydb/blob/main/.github/workflows/regression_run_compatibility.yml

```
      use_default_branches:
        description: 'If true, start main and all current stable branches. If false, start only the selected branch.'
        type: boolean
        required: false
        default: true
```
тоже можно удалить
