### ISSUE TITLE
[stable-25-1-2] Dupms after nightly workloads

### ISSUE THREAD

**Issue by PavelEfarinov** [ydb-platform/ydb#19732]
Did a overnight workloads run for version - `stable-25-1-2.05ccfa6
`
- workload log
- simple queue
- olap
- oltp

Received over 1800 dumps with similar traces: [link](https://coredumps.yandex-team.ru/core?core_hash=620125979950374831&itype=kikimr)

`dmesg` gave a hint about segfault

`[Tue Jun 17 14:45:31 2025] kikimr.User[3472759]: segfault at 0 ip 0000000016f2fab4 sp 00007f3b25e8cc00 error 4 in kikimr[200000+19c8d000]`

Config used to start a cluster:

```yaml
# YDB configuration options and their values
# are described in documentaion https://ydb.tech/en/docs/deploy/configuration/config

# Option will be removed further
use_new_style_kikimr_cfg: true
yaml_config_enabled: true

log:
  cluster_name: "dev-mirror-3-dc" # Change cluster name in order to have better experience with logs searching in Monium.
  sys_log: false
  uaclient_config:
    uri: "[fd53::1]:16400"
    grpc_max_message_size: 4194304

# static erasure is the parameter that
# describes the fault tolerance mode of the
# cluster. See docs for more details https://ydb.tech/en/docs/deploy/configuration/config#domains-blob
static_erasure: mirror-3-dc
host_configs: # the list of available host configurations in the cluster.
  - drive:
      - path: /dev/disk/by-partlabel/kikimr_ssd_01 # path of the first disk in the host configration.
        type: SSD # kind of the disk: available kinds are SSD, SSD or HDD
      - path: /dev/disk/by-partlabel/kikimr_ssd_02
        type: SSD
        # Add more disks if required.
        # NOTE(shmel1k@): If you host has nodeclaim-label like '_4ssd', that means, that
        # they will be located at `kikimr_ssd_01-04`
        # If your host has nodeclaim-label like '_2hdd', that means, that
        # they will be located at `/dev/disk/by-partlabel/kikimr_hdd_03-04` (enumeration starts with 03)
    host_config_id: 1 # the unique id of the host config
hosts:
  - name: myt0-7469.search.yandex.net
    host_config_id: 1
    location:
      body: 1
      data_center: "zone-a"
      rack: "1"
  - name: myt0-7515.search.yandex.net
    host_config_id: 1
    location:
      body: 2
      data_center: "zone-a"
      rack: "2"
  - name: myt0-7520.search.yandex.net
    host_config_id: 1
    location:
      body: 3
      data_center: "zone-a"
      rack: "3"

  - name: myt0-7525.search.yandex.net
    host_config_id: 1
    location:
      body: 4
      data_center: "zone-b"
      rack: "4"
  - name: myt0-7536.search.yandex.net
    host_config_id: 1
    location:
      body: 5
      data_center: "zone-b"
      rack: "5"
  - name: myt0-7538.search.yandex.net
    host_config_id: 1
    location:
      body: 6
      data_center: "zone-b"
      rack: "6"

  - name: myt0-7550.search.yandex.net
    host_config_id: 1
    location:
      body: 7
      data_center: "zone-c"
      rack: "7"
  - name: myt0-7607.search.yandex.net
    host_config_id: 1
    location:
      body: 8
      data_center: "zone-c"
      rack: "8"
  - name: myt0-7628.search.yandex.net
    host_config_id: 1
    location:
      body: 9
      data_center: "zone-c"
      rack: "9"
features:
  EnableSystemViews: True
  EnableParameterizedDecimal: True
  EnableTableDatetime64: True
  EnableSchemeBoard: True
  EnableVectorIndex: True
  EnableSchemeBoardCache: True
# NOTE(shmel1k@): this template domains_config differs from production configuration.
# It will be fixed soon, stay tuned.
domains:
  # There can be only one root domain in a cluster. Domain name prefixes all scheme objects names, e.g. full name of a table table1 in database db1
  # in a cluster with domains_config.domain.name parameter set to Root would be equal to /Root/db1/table1
  - domain_name: Root
    dynamic_slots: 9
    databases:
      - name: "db1"
        storage_units:
          - count: 1 # How many groups will be allocated for database
            kind: ssd # What storage will group use
        compute_units:
          - count: 1 # How many dynamic nodes will database have
            kind: slot
            zone: any
    storage_pool_kinds:
      - kind: ssd
        # fault tolerance mode name - none, block-4-2, or mirror-3-dc.
        # See docs for more details https://ydb.tech/en/docs/deploy/configuration/config#domains-blob
        erasure: mirror-3-dc
        filter_properties:
          type: SSD # device type to match host_configs.drive.type
table_service_config:
  sql_version: 1

sys: # the configuration of the actor system which descibes how cores of the instance are distributed
  executors: # accross different types of workloads in the instance.
    system: # system executor of the actor system. in this executor YDB launches system type of workloads, like system tablets
      threads: 9 # the number of threads allocated to system executor.
      spin_threshold: 1
    user: # user executor of the actor system. In this executor YDB launches user workloads, like datashard activities,
      spin_threshold: 1 # the number of threads allocated to user executor.
      threads: 16 # queries and rpc calls.
    batch: # user executor of the actor system. In this executor YDB launches batch operations, like scan queries, table
      threads: 7 # compactions, background compactions.
      spin_threshold: 1
    io: # the io executor. In this executor launches sync operations and writes logs.
      threads: 1
    ic: # the interconnect executor which YDB uses for network communications accross different nodes of the cluster.
      threads: 3 # the number of threads allocated to the interconnect executor.
      max_threads: 5
      max_avg_ping_deviation: 500
      spin_threshold: 10
      time_per_mailbox_micro_secs: 100
      priority: 40
  scheduler:
    resolution: 64
    spin_threshold: 0
    progress_threshold: 10000

blob_storage_config: # configuration of static blobstorage group.
  # YDB uses this group to store system tablets' data, like SchemeShard
  service_set:
    groups:
      - erasure_species: mirror-3-dc # fault tolerance mode name for the static group
        rings: # in mirror-3-dc must have exactly 3 rings: one in every availability zone.
          - fail_domains:
              - vdisk_locations:
                  - node_id: 1
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 1
              - vdisk_locations:
                  - node_id: 2
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 2
              - vdisk_locations:
                  - node_id: 3
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 3
          - fail_domains:
              - vdisk_locations:
                  - node_id: 4
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 4
              - vdisk_locations:
                  - node_id: 5
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 5
              - vdisk_locations:
                  - node_id: 6
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 6
          - fail_domains:
              - vdisk_locations:
                  - node_id: 7
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 7
              - vdisk_locations:
                  - node_id: 8
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 8
              - vdisk_locations:
                  - node_id: 9
                    pdisk_category: 1
                    path: /dev/disk/by-partlabel/kikimr_ssd_01
                    pdisk_guid: 9
channel_profile_config:
  profile:
    - channel:
        - erasure_species: mirror-3-dc
          pdisk_category: 1
          storage_pool_kind: ssd
        - erasure_species: mirror-3-dc
          pdisk_category: 1
          storage_pool_kind: ssd
        - erasure_species: mirror-3-dc
          pdisk_category: 1
          storage_pool_kind: ssd
      profile_id: 0
interconnect_config:
  start_tcp: true
grpc_config:
  port: 2135

```
