### ISSUE TITLE
Unable to edit static pdisk config with config v2

### ISSUE THREAD

**Issue by rosik** [ydb-platform/ydb#20163]
У меня раздеплоен кластер с конфигурацией v2 следующего вида:

<details><summary>config.yaml</summary>
<p>

```yaml
# Testing configuration: ydynnikov-block-4-2
#
# YDB configuration options and their values are described in
# documentaion https://ydb.tech/en/docs/deploy/configuration/config

metadata:
  kind: MainConfig
  cluster: ""
  version: 0
config:
  yaml_config_enabled: true
  erasure: block-4-2
  default_disk_type: SSD
  self_management_config:
    enabled: true

  domains_config:
    domain:
    - domain_id: 1
      name: Root
      storage_pool_types:
      - kind: ssd
        pool_config:
          box_id: '1'
          erasure_species: block-4-2
          kind: ssd
          pdisk_filter:
          - property:
            - type: SSD
          vdisk_kind: Default

  host_configs:
  - drive:
    - path: /dev/disk/by-partlabel/kikimr_nvme_01
      type: SSD
      expected_slot_count: 9
    - path: /dev/disk/by-partlabel/kikimr_nvme_02
      type: SSD
      expected_slot_count: 9
    - path: /dev/disk/by-partlabel/kikimr_nvme_03
      type: SSD
      expected_slot_count: 9
    - path: /dev/disk/by-partlabel/kikimr_nvme_04
      type: SSD
      expected_slot_count: 9
    host_config_id: 1

  hosts:
  - host: myt0-7678.search.yandex.net
    host_config_id: 1
    node_id: 1
    port: 19000
    location:
      body: 1
      data_center: 'myt0'
      rack: '1'
  - host: myt0-7591.search.yandex.net
    host_config_id: 1
    node_id: 2
    port: 19000
    location:
      body: 2
      data_center: 'myt0'
      rack: '2'
  - host: myt0-7508.search.yandex.net
    host_config_id: 1
    node_id: 3
    port: 19000
    location:
      body: 3
      data_center: 'myt0'
      rack: '3'
  - host: myt0-7490.search.yandex.net
    host_config_id: 1
    node_id: 4
    port: 19000
    location:
      body: 4
      data_center: 'myt0'
      rack: '4'
  - host: myt0-7471.search.yandex.net
    host_config_id: 1
    node_id: 5
    port: 19000
    location:
      body: 5
      data_center: 'myt0'
      rack: '5'
  - host: myt0-7459.search.yandex.net
    host_config_id: 1
    node_id: 6
    port: 19000
    location:
      body: 6
      data_center: 'myt0'
      rack: '6'
  - host: myt0-7440.search.yandex.net
    host_config_id: 1
    node_id: 7
    port: 19000
    location:
      body: 7
      data_center: 'myt0'
      rack: '7'
  - host: myt0-5425.search.yandex.net
    host_config_id: 1
    node_id: 8
    port: 19000
    location:
      body: 8
      data_center: 'myt0'
      rack: '8'

  log_config:
    default_level: 3
    entry:
    - {component: BS_NODE, level: 7}
    - {component: BS_CONTROLLER, level: 7}
    # - {component: GRPC_SERVER, level: 7}
    # - {component: TX_PROXY, level: 7}
    # - {component: TICKET_PARSE, level: 7}
```

</p>
</details> 

Я могу поменять `expected_slot_count` у дисков 02, 03, 04, и после заливки `ydb admin cluster config replace` я даже без рестарта наблюдаю новые значения в Developer UI - Tablets - bsontroller -  Executor DB internals - 103:HostConfigDrive.

Но если поменять конфиг у статического диска 01, то конфиг персистится в cfg_dir, но bscontroller его не применяет, только печатает в лог ошибку:

```
2025-06-25T11:32:56.803861Z :BS_CONTROLLER ERROR: {BSC15@bsc.cpp:432} TEvControllerConfigResponse Response# {Status { ErrorDescription: "PDiskConfig mismatch for static disk NodeId# 1 Path# /dev/disk/by-partlabel/kikimr_nvme_01" FailParam { NodeId: 1 } FailParam { Path: "/dev/disk/by-partlabel/kikimr_nvme_01" } } ErrorDescription: "PDiskConfig mismatch for static disk NodeId# 1 Path# /dev/disk/by-partlabel/kikimr_nvme_01" }
```

Вот полные логи обоих попыток (с узла на котором крутится bscontroller):
- [config_replace_1.log](https://github.com/user-attachments/files/20902799/config_replace_1.log)
- [config_replace_2.log](https://github.com/user-attachments/files/20902797/config_replace_2.log)
