### ISSUE TITLE
Float point exception in plan visualizer

### ISSUE THREAD

**Issue by iddqdex** [ydb-platform/ydb#20328]
Гонял фикс на ветку от @pashandor789, и там всплыла проблема с визуалайзером планов, он пытается делить на ноль, падает и весь cli за собой утягивает.

Вот [стек](https://paste.yandex-team.ru/1612f97d-41fb-4d5d-aeac-261c7e2ac14b)
Вот [отчет с примером падения](https://proxy.sandbox.yandex-team.ru/9078648671/index.html#suites/efe4970bacd9e1454955dc0317c12f5e/f7b11536fbf92b52/)
Команда для воспроизведения (вероятность процентов 50):
```bash
./ydb -p sas_perf_2 workload tpcds --path dt64/column/tpcds/s1 run --json Query78.stats.json --output Query78.result --include Query78 --iterations 3 --plan Query78.plan --global-timeout 1800.0s --verbose --check-canonical --scale 1
```
```yaml
  sas_perf_2:
    endpoint: grpc://c0fhtggrtcjnh4sfq8o3.cluster.testing.ydb.yandex.net:2135
    database: /olap-testing-sas-daily/kikimr/olap/benchmark
```
