### ISSUE TITLE
Docker-compose doesn't work with DNS resolution failed error

### ISSUE THREAD

**Issue by vokson** [ydb-platform/ydb#5128]
Добрый день,

Пытаюсь запустить YDB через docker-compose аналогично тому, как указано здесь https://ydb.tech/docs/ru/quickstart с таким конфигом
```

  ydb:
    container_name: ydb-local
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    platform: linux/amd64
    environment:
      <<: *x-ydb-environment
    ports:
    - "2135:2135"
    - "2136:2136"
    - "8765:8765"
    volumes:
      - ydb_certs:/ydb_certs 
      - ydb_data:/ydb_data
    networks:
      app_network:
        aliases:
          - ydb.lvh.me
```
Если контейнеры общаются между собой, то все ОК. Но, если я пытаюсь законнектится из программы, которая работает не в контейнере (при локальной разработке). Получаю такую ошибку
```
<main>: Error: GRpc error: (14): failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:2136: Ssl handshake failed: SSL_ERROR_SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
<main>: Error: Grpc error response on endpoint localhost:2136
<main>: Error: Endpoint list is empty for database /local, cluster endpoint localhost:2136.
```
Проблема возникает из-за того, что нода имеет свое имя (каждый раз случайное), которое добавляется докером в DNSNames контейнера, но не добавляется в Aliases и поэтому не пингуется.

![image](https://github.com/ydb-platform/ydb/assets/5722616/2f2bcf0c-3e84-4a4a-8452-8969d6e36d47)
![image](https://github.com/ydb-platform/ydb/assets/5722616/bf9c1f6b-decb-4344-a3be-9690028d0671)

Аналогичная проблема с Kuber была описана здесь https://github.com/ydb-platform/ydb/issues/108

На данный момент решил проблему локальной разработки добавлением
hostname: localhost
который нужно убирать при деплое

![image](https://github.com/ydb-platform/ydb/assets/5722616/41a2f7d0-1d61-48b4-a10c-777fc57f7b0e)
![image](https://github.com/ydb-platform/ydb/assets/5722616/85928d6e-51d4-420f-9253-30b6100700b6)

Можно ли как-то решить данную проблему, чтобы docker-compose был одинаковым и для development, и для production

**Comment by lensgolda** [comment]
У меня как-будто обратная проблема

пробую запустить миграции по [инструкции, но в докере](https://ydb.tech/docs/ru/integrations/migration/flyway), предварительно скачав драйвер (версия драйвера `ydb-jdbc-driver-shaded-2.2.11.jar`) и диалект, при запуске миграции ошибка:

```bash
ERROR: No database found to handle jdbc:ydb:grpc://ydb-local:2136/local
```

Конфигурация:

```yaml
version: '3'
services:
  ydb-migrate-local:
    image: flyway/flyway
    command: -url=jdbc:ydb:grpc://ydb-local:2136/local -locations=/flyway/migration migrate
    volumes:
      - ./db/migration:/flyway/migration
      - ./db/drivers:/flyway/libexec/drivers
      - ./db/lib:/flyway/libexec/lib
    depends_on:
      - ydb-local

  ydb-local:
    image: cr.yandex/yc/yandex-docker-local-ydb:latest
    environment:
      GRPC_TLS_PORT: 2135
      GRPC_PORT: 2136
      MON_PORT: 8765
      YDB_DEFAULT_LOG_LEVEL: NOTICE
      YDB_USE_IN_MEMORY_PDISKS: true
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
```

При этом 

<img width="1228" alt="Снимок экрана 2024-10-17 в 10 52 47" src="https://github.com/user-attachments/assets/c8478253-3b56-4577-bd6d-e66c8cee3570">

Перепробовал вроде бы уже разные комбинации с хостами, сетями. Может можно добавить какую-то документацию по применению в докере, или поделиться `docker-compose.yaml`. Буду очень признателен.
