### ISSUE TITLE
[pg] Insert on conflict

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#7194]
```
  - name: 'PG: InsertStmt: not supported onConflictClause'
    count: 1482133
    issue_regexp:
      - 'InsertStmt: not supported onConflictClause'
    example: |
      INSERT INTO table (hostname, updated, max_connections) VALUES ($1, NOW(), $2) 
        ON CONFLICT (hostname) DO UPDATE SET updated = NOW(), max_connections = $2

```
