### ISSUE TITLE
[pg] Generator functions in select

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#7195]
```
  - name: Generator functions in SELECT
    count: 317436
    issue_regexp:
      - '^Generator functions are not allowed in: SELECT$'
    example: SELECT UNNEST($1)
```
