### ISSUE TITLE
Incorrect configuration may lead to segfault 

### ISSUE THREAD

**Issue by minaevmike** [ydb-platform/ydb#72]
Hi,

I'm trying to run ydb in "strange" configuration - 2 nodes(just for testing purposes). 
I have the following configuration file
```
static_erasure: none
host_configs:
  - drive:
      - path: ydb.data
        type: SSD
    host_config_id: 1
hosts:
  - host: host1.test
    host_config_id: 1
    port: 19001
    walle_location:
      body: 1
      data_center: '1'
      rack: '1'
  - host: host2.test
    host_config_id: 1
    port: 19001
    walle_location:
      body: 2
      data_center: '2'
      rack: '2'
domains_config:
  domain:
    - name: Root
      storage_pool_types:
        - kind: ssd
          pool_config:
            box_id: 1
            erasure_species: none
            kind: ssd
            pdisk_filter:
              - property:
                  - type: SSD
            vdisk_kind: Default
  state_storage:
    - ring:
        node: [1,2]
        nto_select: 2
      ssid: 1
table_service_config:
  sql_version: 1
actor_system_config:
  executor:
    - name: System
      spin_threshold: 0
      threads: 2
      type: BASIC
    - name: User
      spin_threshold: 0
      threads: 3
      type: BASIC
    - name: Batch
      spin_threshold: 0
      threads: 2
      type: BASIC
    - name: IO
      threads: 1
      time_per_mailbox_micro_secs: 100
      type: IO
    - name: IC
      spin_threshold: 10
      threads: 1
      time_per_mailbox_micro_secs: 100
      type: BASIC
  scheduler:
    progress_threshold: 10000
    resolution: 256
    spin_threshold: 0
blob_storage_config:
  service_set:
    groups:
      - erasure_species: none
        rings:
          - fail_domains:
              - vdisk_locations:
                  - node_id: host1.test
                    path: ydb.data
                    pdisk_category: SSD
          - fail_domains:
             - vdisk_locations:
                  - node_id: host2.test
                    path: ydb.data
                    pdisk_category: SSD
channel_profile_config:
  profile:
    - channel:
        - erasure_species: none
          pdisk_category: 0
          storage_pool_kind: ssd
        - erasure_species: none
          pdisk_category: 0
          storage_pool_kind: ssd
        - erasure_species: none
          pdisk_category: 0
          storage_pool_kind: ssd
      profile_id: 0
``` 
When i run server with this config i've got 
```
$ ./start.sh disk
Starting storage process...
./start.sh: line 27: 10017 Segmentation fault      `pwd`/ydbd/bin/ydbd server --yaml-config $cfg --node static --grpc-port 2136 --ic-port 19001 --mon-port 8765 --log-file-name logs/storage_start.log > logs/storage_start_output.log 2> logs/storage_start_err.log
Registering database ...
Errors found when registering database, cancelling start script, check logs/db_reg.log
$ cat logs/db_reg.log
GRPC call error: failed to connect to all addresses
```

So what I'm doing wrong? Is it possible to start the server if the server on `host2.test` did not start yet?

**Comment by mvgorbunov** [comment]
Does it works in single node local mode with default config on same server?

**Comment by minaevmike** [comment]
Yes. In a single node mode, it works perfectly.

**Comment by mvgorbunov** [comment]
First of all, you should fix your config:
1. state_storage - ring should have odd number of nodes (1, 3, 5, etc)
```
  state_storage:
    - ring:
        node:
        - 1
        nto_select: 1
      ssid: 1
``` 
2. blob_storage_config - remove host2.test (or you have to wait until host2.test starts)
```
blob_storage_config:
  service_set:
    groups:
      - erasure_species: none
        rings:
          - fail_domains:
              - vdisk_locations:
                  - node_id: host1.test
                    path: ydb.data
                    pdisk_category: SSD
```
But I tried to use your config - I got some errors, but not Segmentation fault .
