### ISSUE TITLE
Switch cluster to new registernode+certs

### ISSUE THREAD

**Issue by UgnineSirdis** [ydb-platform/ydb#7728]
YDBOPS-6393
* На хостах разложены сертификаты (надо уточнить как именно использовать на ВМ) Сертификаты должны быть клиент-серверными

* Добавляем в параметры запуска диннод

Указываем порт для node broker, совпадающий с grpcs портом статической ноды
Пример:

```--node-broker-port 2136```

Ставим флаг командной строки node-broker-use-tls в true
Пример:

```--node-broker-use-tls true```

Передаем клиентские сертификаты
Пример:
```
--grpc-ca=/path/to/ca.crt
--grpc-cert=/path/to/client.crt
--grpc-key=/path/to/client.key
```
* Делаем рестарт диннод

* Обновляем конфигурацию статических нод

Указываем настройки для grpcs соединения
Пример:
```
grpc_config:
  services: [legacy, discovery]
  ssl_port: 2136
  ca: "/path/to/ca.crt"
  cert: "/path/to/server.crt"
  key: "/path/to/server.key"
```
Конфигурационном файле указать авторизационные данные, по которым будут авторизовываться ноды, пришедшие на регистрацию.
Пример:
```
client_certificate_authorization:
  request_client_certificate: true
  client_certificate_definitions:
    - member_groups: ["firstGroup@cert", "secondGroups@cert"]
      subject_terms:
      - short_name: "C"
        values: ["RU"]
      - short_name: "ST"
        values: ["Moscow"]
      - short_name: "L"
        values: ["Moscow"]
      - short_name: "O"
        values: ["Yandex.Cloud"]
      - short_name: "OU"
        values: ["Infra"]
      - short_name: "CN"
        values: ["www.example.ru"]
        suffixes: [".example1.net", ".example2.ru", ".example3.co.il"]
```
* Включить требование токена на статических нодах и добавить в список register_dynamic_node_allowed_sids имена групп добавленных в предыдущем пункте в атрибуте member_groups и, на переходный период, сид root@builtin
```
security_config:
  enforce_user_token_requirement: true
  register_dynamic_node_allowed_sids:
  - firstGroup@cert
  - root@builtin
```
Сделать рестарт статических нод

=Пример с реальным сертификатом=

Пусть есть такой клиентский сертификат
```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            48:e8:a3:98:af:e9:ea:d3:99:c1:d1:a1:2f:d0:65:ea:07:de:5f:1c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = FR, ST = Occitanie, L = Toulouse, O = Tech School, OU = Education, CN = *.techschool.guru, emailAddress = techschool.guru@gmail.com
        Validity
            Not Before: May 18 17:53:04 2024 GMT
            Not After : Jul 17 17:53:04 2024 GMT
        Subject: C = FR, ST = Alsace, L = Strasbourg, O = PC Client, OU = Computer, CN = *.pcclient.com, emailAddress = pcclient@gmail.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
                Modulus:
...
```
Тогда для проверки такого сертификата, конфигурация может содержать
```
client_certificate_authorization:
  request_client_certificate: true
  client_certificate_definitions:
    - member_groups: ["registerNodeFR@cert"]
      subject_terms:
      - short_name: "C"
        values: ["FR"]
      - short_name: "ST"
        values: ["Alsace"]
      - short_name: "L"
        values: ["Strasbourg"]
      - short_name: "O"
        values: ["PC Client"]
      - short_name: "OU"
        values: ["Computer"]
      - short_name: "CN"
        values: []
        suffixes: [".pcclient.com"]
    - member_groups: ["registerNodeSimple@cert"] # Чтобы попасть в эту группу нужно совпадение лишь одного атрибута
      subject_terms:
      - short_name: "C"
        values: ["FR"]
```
