### ISSUE TITLE
Configure CPU distribution for CL tenants:

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#9622]
Tenants:
preprod:
/pre-prod_vla/yc.logs.cloud/cc8jliaf18k2b9ae2bio
/pre-prod_sas/yc.logs.cloud/cc8bajrmntk9q0d1lc0t
/pre-prod_klg/yc.logs.cloud/cc817gnjjceirp80h587
/pre-prod_global/yc.logs.cloud/cc803vrb3afsn32c43cb

prod
/vla/yc.logs.cloud/etn9p8577052puat48co
/sas/yc.logs.cloud/etng9ariostodmvtu6v7
/klg/yc.logs.cloud/etnja0qqnqgrjipkum9h
/global/yc.logs.cloud/etn035ga3gnd0d3lm7ds

```
settings:
scan_conveyor_config: !inherit
  worker_count: 4
сomp_conveyor_config: !inherit
  worker_count: 1
```
